name: NPM CI
on:
  push:
    paths-ignore:
      - "docs/**"

jobs:
  npm-ci-job:
    name: "YARN & NPM Build Test"
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - name: "YARN install"
        run: yarn install --frozen-lockfile
      - name: "NPM run build"
        run: |
          npm run build
          npm run build:types
      - run: | 
          npm run lint
      - run: | 
          npx lerna run --stream --concurrency=1 test:ci
      - run: |
          npm run test:bs